version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.2
    ports:
        - 9200:9200
        - 9300:9300
    environment:
        - 'ES_JAVA_OPTS=-Xms2048m -Xmx2048m'
        - 'discovery.type=single-node'
    volumes:
        - elasticsearch-data:/mnt/c/Users/jortu/OneDrive/Escritorio/Jon/Universidad/4 de Carrera/AS/Grupal/Datos
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
volumes:
  elasticsearch-data:
    external: true  