apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-01-06T17:29:57Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  generateName: es-cluster-0-
  labels:
    app: elasticsearch
    controller-revision-hash: es-cluster-6bd9b488b7
    statefulset.kubernetes.io/pod-name: es-cluster-0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
          f:controller-revision-hash: {}
          f:statefulset.kubernetes.io/pod-name: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":9200,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:controller-revision-hash: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2022-01-06T17:29:57Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-06T17:30:30Z"
  name: es-cluster-0-crv2w
  namespace: kube-logging
  resourceVersion: "563910"
  uid: 154e0121-a7ee-4d47-8209-931ec64ee9d7
spec:
  clusterIP: 10.104.10.162
  clusterIPs:
  - 10.104.10.162
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30046
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
    controller-revision-hash: es-cluster-6bd9b488b7
    statefulset.kubernetes.io/pod-name: es-cluster-0
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.195.149.133
